// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// row_mean_grouped_dgcmatrix
NumericMatrix row_mean_grouped_dgcmatrix(S4 matrix, IntegerVector group_labels, bool shuffle);
RcppExport SEXP _riffle_row_mean_grouped_dgcmatrix(SEXP matrixSEXP, SEXP group_labelsSEXP, SEXP shuffleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_labels(group_labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type shuffle(shuffleSEXP);
    rcpp_result_gen = Rcpp::wrap(row_mean_grouped_dgcmatrix(matrix, group_labels, shuffle));
    return rcpp_result_gen;
END_RCPP
}
// row_mean_grouped_dense
NumericMatrix row_mean_grouped_dense(NumericMatrix matrix, IntegerVector group_labels, bool shuffle);
RcppExport SEXP _riffle_row_mean_grouped_dense(SEXP matrixSEXP, SEXP group_labelsSEXP, SEXP shuffleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_labels(group_labelsSEXP);
    Rcpp::traits::input_parameter< bool >::type shuffle(shuffleSEXP);
    rcpp_result_gen = Rcpp::wrap(row_mean_grouped_dense(matrix, group_labels, shuffle));
    return rcpp_result_gen;
END_RCPP
}
// row_nonzero_count_grouped_dgcmatrix
IntegerMatrix row_nonzero_count_grouped_dgcmatrix(S4 matrix, IntegerVector group_labels);
RcppExport SEXP _riffle_row_nonzero_count_grouped_dgcmatrix(SEXP matrixSEXP, SEXP group_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_labels(group_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(row_nonzero_count_grouped_dgcmatrix(matrix, group_labels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_riffle_row_mean_grouped_dgcmatrix", (DL_FUNC) &_riffle_row_mean_grouped_dgcmatrix, 3},
    {"_riffle_row_mean_grouped_dense", (DL_FUNC) &_riffle_row_mean_grouped_dense, 3},
    {"_riffle_row_nonzero_count_grouped_dgcmatrix", (DL_FUNC) &_riffle_row_nonzero_count_grouped_dgcmatrix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_riffle(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
