# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_mean_grouped_dgcmatrix <- function(matrix, group_labels, shuffle) {
    .Call('_riffle_row_mean_grouped_dgcmatrix', PACKAGE = 'riffle', matrix, group_labels, shuffle)
}

row_mean_grouped_dense <- function(matrix, group_labels, shuffle) {
    .Call('_riffle_row_mean_grouped_dense', PACKAGE = 'riffle', matrix, group_labels, shuffle)
}

row_nonzero_count_grouped_dgcmatrix <- function(matrix, group_labels) {
    .Call('_riffle_row_nonzero_count_grouped_dgcmatrix', PACKAGE = 'riffle', matrix, group_labels)
}

